repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: '23.7.0'
    hooks:
    -   id: black
        args: [--config=pyproject.toml]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 26de894
    hooks:
    - id: mypy
      additional_dependencies:
        - 'numpy'
      args: [--ignore-missing-imports, --warn-no-return, --warn-redundant-casts, --disallow-incomplete-defs, --no-namespace-packages]
-   repo: https://gitlab.com/pycqa/flake8
    rev: '5.0.4'
    hooks:
    -   id: flake8
        additional_dependencies: [
                'flake8-bugbear==22.8.23',
                'flake8-coding==1.3.2',
                'flake8-comprehensions==3.10.0',
                'flake8-debugger==4.1.2',
                'flake8-deprecated==1.3',
                'flake8-docstrings==1.6.0',
                'flake8-isort==4.2.0',
                'flake8-pep3101==1.3.0',
                'flake8-polyfill==1.0.2',
                'flake8-print==5.0.0',
                'flake8-quotes==3.3.1',
                'flake8-string-format==0.3.0',
        ]
